#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cartesianMesh -case cases/fluid-domena
#cartesianMesh -case cases/solid-domena
tetMesh -case cases/solid-domena

cp -r cases/fluid-domena/constant/polyMesh/ constant/fluid-domena
cp -r cases/solid-domena/constant/polyMesh/ constant/solid-domena

# remove fluid fields from solid regions (important for post-processing)


rm -f 0*/solid-domena/p_rgh
rm -f 0*/solid-domena/epsilon
rm -f 0*/solid-domena/U

changeDictionary -region fluid-domena
changeDictionary -region solid-domena


#chtMultiRegionFoam
