#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication ./Allrun

runApplication decomposePar -allRegions
runParallel $(getApplication)

runApplication reconstructPar -allRegions