#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication ./Allrun

runApplication decomposePar -allRegions

runParallel $(getApplication)

runApplication reconstructPar -allRegions

# for region in fluid-domena solid-domena; do
#     foamToVTK -region $region -latestTime
# done

# conda env activate pyfoam-env

# python3 extract_outlet_temperatures_pure.py

paraFoam